language: node_js
node_js: node
cache:
  yarn: true
  directories:
    - node_modules
git:
  quiet: true
  submodules: false
notifications:
  email: false
jobs:
  include:
    - script: yarn test
    - stage: deploy
      script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
    - script: yarn semantic-release
