language: node_js
node_js: node
cache:
  yarn: true
  directories:
    - node_modules
git:
  quiet: true
  submodules: false
notifications:
  email: false
before_install: mkdir -p ~/$TRAVIS_BUILD_NUMBER
jobs:
  include:
    - script:
      - yarn test
      - cp ./coverage/lcov.info ~/$TRAVIS_BUILD_NUMBER/lcov.info
    - stage: deploy
      name: Coverage
      script: cat ~/$TRAVIS_BUILD_NUMBER/lcov.info | ./node_modules/coveralls/bin/coveralls.js
    - name: Release
      script: yarn semantic-release
