language: node_js
cache:
  yarn: true
  directories:
    - node_modules
git:
  quiet: true
  submodules: false
notifications:
  email: false
node_js: lts/*
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - yarn travis-deploy-once "yarn semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
